#server:
#  port: 8082
#spring:
#  datasource:
#    driveClassName: org.h2.Driver
#    password: password
#    url: jdbc:h2:mem:dcbapp
#    username: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#welcome:
#  message: Welcome to new Spring boot project to check Hey seriii ok so assitent will check Artificail Intelligent everything..!!
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,bean"